### ISSUE TITLE
Síntesis Gestión de Proyectos

### ISSUE THREAD

**Issue by Band-hi** [SistemasTecTlaxiaco/actividad-3-sintesis-Band-hi#2]
Síntesis

**Comment by Band-hi** [comment]
[Síntesis - Gandhi Salazar Cruz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-Band-hi/files/9466220/Sintesis.-.Gandhi.Salazar.Cruz.pdf)

**Comment by kirus21** [comment]
16/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
